modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Viola-Siemens/Survive-in-the-Winter-Frontier/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="logo.png"
    credits="Hexagram"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.misc_twf]]
    modId="neoforge"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="minecraft"
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="createaddition"
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="curios"
    versionRange="[9,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="expandability"
    versionRange="[12,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="hordes"
    versionRange="[1.5.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="jade"
    versionRange="[5.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="travelersbackpack"
    versionRange="[1.21.1-10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.misc_twf]]
    modId="tetrachordlib"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
